---
- hosts: all
  vars:
    docker_images:
     - jenkins
     - errbot/err
     - python
       #     cannot use with mattermost preview
       #     - adelton/freeipa-server
     - mattermost/mattermost-preview
     - sentry
     - redis
     - postgres
     - gitlab/gitlab-ce
  tasks:
  - shell: 'curl -sSL https://get.docker.com/ | sh'
  - apt: name=python-pip state=present
  - pip: name=docker-py state=present
  - pip: name=docker-compose state=present
  - command: docker pull {{item}}
    with_items: "{{docker_images}}"
