---
- hosts: all
  tasks:
  - copy: src=jenkins.Dockerfile dest=/root/Dockerfile
  - command: chdir=/root docker build -t myjenkins .
  - command: >
          docker run -dp 8080:8080
          -v /var/run/docker.sock:/var/run/docker.sock
          -v /usr/bin/docker:/usr/bin/docker
          myjenkins
