---
- hosts: all
  gather_facts: False
  tasks:
  - copy: src=jenkins.Dockerfile dest=/root/Dockerfile
  - command: chdir=/root docker build -t myjenkins .
  - docker:
      name: jenkins
      image: myjenkins
      ports:
        - "8888:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/usr/bin/docker:/usr/bin/docker"
